spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enable: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    hikari:
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
